Repository codesquad-team4-issue-tracker/issue-tracker-max, pull requests merged in 2023-08, with the labels that each got.

#25 [BE] Oauth 테스트 작성
  be/src/main/java/com/issuetrackermax/service/member/MemberService.java
  be/src/main/java/com/issuetrackermax/service/oauth/OauthService.java
  be/src/test/java/com/issuetrackermax/service/oauth/OauthProviderTest.java
  be/src/test/java/com/issuetrackermax/service/oauth/OauthServiceTest.java
Labels: test, BE

#26 [BE] 이슈 작성 및 상세 페이지 구현
  .github/ISSUE_TEMPLATE/custom.md
  be/src/main/java/com/issuetrackermax/controller/filter/dto/AssigneeResponse.java
  be/src/main/java/com/issuetrackermax/controller/issue/IssueController.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssueApplyRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssuePostRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssueTitleRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssuesStatusRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/response/IssueDetailsResponse.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/response/IssuePostResponse.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/history/HistoryRepository.java
  be/src/main/java/com/issuetrackermax/domain/history/entity/History.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueRepository.java
  be/src/main/java/com/issuetrackermax/domain/issue/entity/IssueResultVO.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
Labels: feat, BE

#33 [BE] 필터링을 추가한다.
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/controller/filter/FilterController.java
  be/src/main/java/com/issuetrackermax/controller/filter/dto/FilterRequest.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/filter/FilterMapper.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueCommentRepository.java
  be/src/main/java/com/issuetrackermax/service/filter/FilterService.java
  be/src/main/java/com/issuetrackermax/service/filter/dto/FilterInformation.java
  be/src/main/resources/mybatis/FilterMapper.xml
  be/src/test/java/com/issuetrackermax/controller/filter/FilterControllerTest.java
  be/src/test/java/com/issuetrackermax/domain/filter/FilterMapperTest.java
  be/src/test/java/com/issuetrackermax/fixture/EntityFixture.java
  be/src/test/java/com/issuetrackermax/service/filter/FilterServiceTest.java
  be/src/test/java/com/issuetrackermax/service/oauth/OauthProviderTest.java
  be/src/test/java/com/issuetrackermax/service/oauth/OauthServiceTest.java
Labels: feat, test, BE

#32 [BE] 이슈 상세페이지 예외 처리 및 id 검증 추가
  be/build.gradle
  be/src/main/java/com/issuetrackermax/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/issuetrackermax/common/exception/InvalidIssueStatusException.java
  be/src/main/java/com/issuetrackermax/common/exception/NotFoundAssigneeException.java
  be/src/main/java/com/issuetrackermax/common/exception/NotFoundHistoryException.java
  be/src/main/java/com/issuetrackermax/common/exception/NotFoundIssueException.java
  be/src/main/java/com/issuetrackermax/common/exception/NotFoundLabelException.java
  be/src/main/java/com/issuetrackermax/common/exception/NotFoundMilestoneException.java
  be/src/main/java/com/issuetrackermax/controller/issue/IssueController.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssuePostRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssueTitleRequest.java
  be/src/main/java/com/issuetrackermax/domain/assignee/AssigneeRepository.java
  be/src/main/java/com/issuetrackermax/domain/history/HistoryRepository.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueRepository.java
  be/src/main/java/com/issuetrackermax/domain/label/LabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/MilestoneRepository.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
Labels: feat, refactor, BE

#48 [BE] CORS설정
  be/src/main/java/com/issuetrackermax/config/CorsConfig.java
Labels: chore, BE

#47 [BE] CI/CD 설정
  .github/workflows/cicd.yml
  docker-compose-dev.yml
  nginx/nginx-dev.conf
Labels: chore, BE

#52 [BE] 레이블 & 마일스톤 CRUD 기능 구현
  be/src/main/java/com/issuetrackermax/controller/assignee/AssigneeController.java
  be/src/main/java/com/issuetrackermax/controller/auth/AuthController.java
  be/src/main/java/com/issuetrackermax/controller/auth/OAuthController.java
  be/src/main/java/com/issuetrackermax/controller/comment/CommentController.java
  be/src/main/java/com/issuetrackermax/controller/filter/FilterController.java
  be/src/main/java/com/issuetrackermax/controller/issue/IssueController.java
  be/src/main/java/com/issuetrackermax/controller/label/LabelController.java
  be/src/main/java/com/issuetrackermax/controller/member/MemberController.java
  be/src/main/java/com/issuetrackermax/controller/milestone/MilestoneController.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/request/MilestoneModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/request/MilestonePostRequest.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/response/MilestoneCloseResponse.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/response/MilestoneDetailResponse.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/response/MilestoneOpenResponse.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/response/MilestonePostResponse.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/MilestoneRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/entity/Milestone.java
  be/src/main/java/com/issuetrackermax/service/milestone/MilestoneService.java
  be/src/test/java/com/issuetrackermax/controller/ControllerTestSupport.java
  be/src/test/java/com/issuetrackermax/controller/auth/AuthControllerTest.java
  be/src/test/java/com/issuetrackermax/controller/filter/FilterControllerTest.java
  be/src/test/java/com/issuetrackermax/controller/label/LabelControllerTest.java
  be/src/test/java/com/issuetrackermax/controller/member/MemberControllerTest.java
  be/src/test/java/com/issuetrackermax/controller/milestone/MilestoneControllerTest.java
  be/src/test/java/com/issuetrackermax/service/milestone/MilestoneServiceTest.java
Labels: feat, BE

#59 [BE] 이슈 작성 및 상세 페이지 테스트 코드 작성
  be/src/main/java/com/issuetrackermax/common/exception/ApiException.java
  be/src/main/java/com/issuetrackermax/common/exception/domain/AssigneeException.java
  be/src/main/java/com/issuetrackermax/config/HistoryAspect.java
  be/src/main/java/com/issuetrackermax/controller/issue/IssueController.java
  be/src/main/java/com/issuetrackermax/controller/label/LabelController.java
  be/src/main/java/com/issuetrackermax/domain/assignee/AssigneeRepository.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueLabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/MilestoneRepository.java
  be/src/main/java/com/issuetrackermax/service/assignee/AssigneeService.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
  be/src/main/java/com/issuetrackermax/service/milestone/MilestoneService.java
  be/src/test/java/com/issuetrackermax/controller/ControllerTestSupport.java
  be/src/test/java/com/issuetrackermax/controller/issue/IssueControllerTest.java
  be/src/test/java/com/issuetrackermax/controller/milestone/MilestoneControllerTest.java
  be/src/test/java/com/issuetrackermax/domain/issue/IssueRepositoryTest.java
  be/src/test/java/com/issuetrackermax/service/history/HistoryServiceTest.java
  be/src/test/java/com/issuetrackermax/service/issue/IssueServiceTest.java
  be/src/test/java/com/issuetrackermax/service/jwt/JwtServiceTest.java
  be/src/test/java/com/issuetrackermax/service/milestone/MilestoneServiceTest.java
Labels: BE

#60 [BE]3주차 작업 병합
  be/build.gradle
  be/src/main/java/com/issuetrackermax/common/exception/ApiException.java
  be/src/main/java/com/issuetrackermax/common/exception/domain/AssigneeException.java
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/config/HistoryAspect.java
  be/src/main/java/com/issuetrackermax/controller/auth/AuthController.java
  be/src/main/java/com/issuetrackermax/controller/auth/dto/request/LogoutRequest.java
  be/src/main/java/com/issuetrackermax/controller/history/dto/HistoryRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/IssueController.java
  be/src/main/java/com/issuetrackermax/controller/label/LabelController.java
  be/src/main/java/com/issuetrackermax/controller/milestone/MilestoneController.java
  be/src/main/java/com/issuetrackermax/domain/assignee/AssigneeRepository.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/history/HistoryRepository.java
  be/src/main/java/com/issuetrackermax/domain/history/entity/History.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueLabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueRepository.java
  be/src/main/java/com/issuetrackermax/domain/jwt/JwtRepository.java
  be/src/main/java/com/issuetrackermax/domain/label/LabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/member/MemberRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/MilestoneRepository.java
  be/src/main/java/com/issuetrackermax/service/assignee/AssigneeService.java
  be/src/main/java/com/issuetrackermax/service/comment/CommentService.java
  be/src/main/java/com/issuetrackermax/service/filter/FilterService.java
  be/src/main/java/com/issuetrackermax/service/history/HistoryService.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
  be/src/main/java/com/issuetrackermax/service/jwt/JwtService.java
  be/src/main/java/com/issuetrackermax/service/label/LabelService.java
  be/src/main/java/com/issuetrackermax/service/milestone/MilestoneService.java
  be/src/test/java/com/issuetrackermax/controller/ControllerTestSupport.java
  be/src/test/java/com/issuetrackermax/controller/issue/IssueControllerTest.java
  be/src/test/java/com/issuetrackermax/controller/milestone/MilestoneControllerTest.java
  be/src/test/java/com/issuetrackermax/domain/filter/FilterMapperTest.java
  be/src/test/java/com/issuetrackermax/domain/issue/IssueRepositoryTest.java
  be/src/test/java/com/issuetrackermax/service/filter/FilterServiceTest.java
  be/src/test/java/com/issuetrackermax/service/history/HistoryServiceTest.java
  be/src/test/java/com/issuetrackermax/service/issue/IssueServiceTest.java
  be/src/test/java/com/issuetrackermax/service/jwt/JwtServiceTest.java
  be/src/test/java/com/issuetrackermax/service/label/LabelServiceTest.java
  be/src/test/java/com/issuetrackermax/service/milestone/MilestoneServiceTest.java
Labels: feat, BE

#66 [FE] 로그인 및 회원가입 기능 구현
  fe/.gitignore
  fe/src/components/Header/Header.tsx
  fe/src/components/Sign/SignIn.tsx
  fe/src/components/Sign/SignUp.tsx
  fe/src/components/Sign/common/CheckValidInfo.tsx
  fe/src/components/Sign/common/InputWithValidation.tsx
  fe/src/components/Sign/common/UserInput.tsx
  fe/src/constant/regex.ts
  fe/src/useFetch.ts
  fe/src/util/customFetch.ts
Labels: feat, FE

#76 [FE] 로그인 및 회원가입 기능 구현
  fe/src/App.tsx
  fe/src/components/Issue/IssueList/CheckBox.tsx
  fe/src/components/Issue/IssueList/IssueContext.tsx
  fe/src/components/Issue/IssueList/IssueFilter.tsx
  fe/src/components/Issue/IssueList/IssueItem.tsx
  fe/src/components/Issue/IssueList/IssueList.tsx
  fe/src/components/Label/Label.tsx
  fe/src/components/Label/LabelContext.tsx
  fe/src/components/Label/LabelItem.tsx
  fe/src/components/Label/LabelList.tsx
  fe/src/components/Milestone/MilestoneButton.tsx
  fe/src/components/Milestone/MilestoneContext.tsx
  fe/src/components/Milestone/MilestoneFilter.tsx
  fe/src/components/Milestone/MilestoneItem.tsx
  fe/src/components/Milestone/MilestoneList.tsx
  fe/src/components/SubNavbar.tsx
  fe/src/components/common/Button.tsx
  fe/src/constant/constant.ts
  fe/src/constant/regex.ts
  fe/src/type/issue.d.ts
  fe/src/type/label.d.ts
  fe/src/type/milestone.d.ts
Labels: feat, refactor, FE

#88 [FE] 이슈 생성 페이지 뼈대 생성 및 파일 경로 수정
  fe/src/App.tsx
  fe/src/components/FilterBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Issue/IssueCreate/IssueCreate.tsx
  fe/src/components/Issue/IssueList/CheckBox.tsx
  fe/src/components/Issue/IssueList/DropdownIndicator.tsx
  fe/src/components/Issue/IssueList/IssueFilter.tsx
  fe/src/components/Issue/IssueList/IssueItem.tsx
  fe/src/components/Label/LabelItem.tsx
  fe/src/components/Milestone/MilestoneFilter.tsx
  fe/src/components/Milestone/MilestoneItem.tsx
  fe/src/components/Sign/SignIn.tsx
  fe/src/components/Sign/SignUp.tsx
  fe/src/components/SubNavbar.tsx
  fe/src/components/ThemeToggle.tsx
  fe/src/components/common/Taps.tsx
Labels: FE

#94 [FE] 이슈 생성, 이슈 상세 페이지 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/assets/icon/caption.svg
  fe/src/components/Header/Header.tsx
  fe/src/components/Issue/IssueContent.tsx
  fe/src/components/Issue/IssueCreate/IssueCreate.tsx
  fe/src/components/Issue/IssueCreate/SidebarCreate.tsx
  fe/src/components/Issue/IssueDetail/Comment.tsx
  fe/src/components/Issue/IssueDetail/IssueDetail.tsx
  fe/src/components/Issue/IssueDetail/IssueDetailHeader.tsx
  fe/src/components/Issue/IssueDetail/SidebarDetail.tsx
  fe/src/components/Issue/IssueList/CheckBox.tsx
  fe/src/components/Issue/IssueList/IssueFilter.tsx
  fe/src/components/Issue/IssueList/IssueItem.tsx
  fe/src/components/Issue/IssueList/IssueList.tsx
  fe/src/components/Label/LabelList.tsx
  fe/src/components/Milestone/MilestoneFilter.tsx
  fe/src/components/Milestone/MilestoneItem.tsx
  fe/src/components/Milestone/MilestoneList.tsx
  fe/src/components/Sign/SignIn.tsx
  fe/src/components/Sign/SignUp.tsx
  fe/src/components/SubNavbar.tsx
  fe/src/components/common/Button.tsx
  fe/src/styles/styles.ts
  fe/src/type/issue.d.ts
  fe/src/type/label.d.ts
  fe/src/util/customFetch.ts
  fe/src/util/getFormatDate.ts
  fe/src/util/getTimeLine.ts
Labels: feat, design, FE

#75 [BE] label, milestone request valid 설정
  be/src/main/java/com/issuetrackermax/controller/label/LabelController.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/request/LabelModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/request/LabelPostRequest.java
  be/src/main/java/com/issuetrackermax/controller/milestone/MilestoneController.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/request/MilestoneModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/request/MilestonePostRequest.java
Labels: feat, BE

#81 [BE]회원가입 아이디 중복체크 api 구현
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/controller/member/MemberController.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/request/CheckLoginIdRequest.java
  be/src/main/java/com/issuetrackermax/service/member/MemberService.java
  be/src/test/java/com/issuetrackermax/controller/member/MemberControllerTest.java
  be/src/test/java/com/issuetrackermax/domain/member/MemberRepositoryTest.java
Labels: feat, BE

#101 [BE] Comment CRUD기능 구현
  be/build.gradle
  be/src/main/java/com/issuetrackermax/common/exception/domain/CommentException.java
  be/src/main/java/com/issuetrackermax/common/exception/domain/S3Exception.java
  be/src/main/java/com/issuetrackermax/common/util/CommonUtil.java
  be/src/main/java/com/issuetrackermax/controller/comment/CommentController.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentCreateRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/response/CommentResponse.java
  be/src/main/java/com/issuetrackermax/controller/filter/FilterController.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssuePostRequest.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentValidator.java
  be/src/main/java/com/issuetrackermax/domain/comment/entity/Comment.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueCommentRepository.java
  be/src/main/java/com/issuetrackermax/service/comment/CommentService.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
  be/src/main/resources/mybatis/FilterMapper.xml
  be/src/test/java/com/issuetrackermax/domain/comment/CommentRepositoryTest.java
  be/src/test/java/com/issuetrackermax/domain/filter/FilterMapperTest.java
  be/src/test/java/com/issuetrackermax/fixture/EntityFixture.java
  be/src/test/java/com/issuetrackermax/service/comment/CommentServiceTest.java
Labels: feat, BE

#102 [BE] Comment CRUD기능 구현
  be/build.gradle
  be/src/main/java/com/issuetrackermax/common/exception/domain/CommentException.java
  be/src/main/java/com/issuetrackermax/common/exception/domain/S3Exception.java
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/common/util/CommonUtil.java
  be/src/main/java/com/issuetrackermax/controller/comment/CommentController.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentCreateRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/response/CommentResponse.java
  be/src/main/java/com/issuetrackermax/controller/filter/FilterController.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssuePostRequest.java
  be/src/main/java/com/issuetrackermax/controller/label/LabelController.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/request/LabelModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/request/LabelPostRequest.java
  be/src/main/java/com/issuetrackermax/controller/member/MemberController.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/request/CheckLoginIdRequest.java
  be/src/main/java/com/issuetrackermax/controller/milestone/MilestoneController.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/request/MilestoneModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/request/MilestonePostRequest.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentValidator.java
  be/src/main/java/com/issuetrackermax/domain/comment/entity/Comment.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueCommentRepository.java
  be/src/main/java/com/issuetrackermax/service/comment/CommentService.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
  be/src/main/java/com/issuetrackermax/service/member/MemberService.java
  be/src/main/resources/mybatis/FilterMapper.xml
  be/src/test/java/com/issuetrackermax/controller/member/MemberControllerTest.java
  be/src/test/java/com/issuetrackermax/domain/comment/CommentRepositoryTest.java
  be/src/test/java/com/issuetrackermax/domain/filter/FilterMapperTest.java
  be/src/test/java/com/issuetrackermax/domain/member/MemberRepositoryTest.java
  be/src/test/java/com/issuetrackermax/fixture/EntityFixture.java
  be/src/test/java/com/issuetrackermax/service/comment/CommentServiceTest.java
Labels: feat, BE

#107 [BE] 댓글 작성자 이미지 조회 기능, 아이디 중복 체크 기능 추가
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/controller/comment/CommentController.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentCreateRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/response/CommentResponse.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssuePostRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/response/IssueDetailsResponse.java
  be/src/main/java/com/issuetrackermax/controller/member/MemberController.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/request/CheckLoginIdRequest.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/comment/entity/Comment.java
  be/src/main/java/com/issuetrackermax/domain/comment/entity/CommentMemberVO.java
  be/src/main/java/com/issuetrackermax/domain/member/MemberRepository.java
  be/src/main/java/com/issuetrackermax/service/comment/CommentService.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
  be/src/main/java/com/issuetrackermax/service/member/MemberService.java
  be/src/test/java/com/issuetrackermax/controller/auth/AuthControllerTest.java
  be/src/test/java/com/issuetrackermax/domain/comment/CommentRepositoryTest.java
  be/src/test/java/com/issuetrackermax/domain/member/MemberRepositoryTest.java
  be/src/test/java/com/issuetrackermax/fixture/EntityFixture.java
  be/src/test/java/com/issuetrackermax/service/comment/CommentServiceTest.java
Labels: feat, BE

#108 [BE] 4주차 1차 PR
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/controller/auth/dto/response/MemberProfileResponse.java
  be/src/main/java/com/issuetrackermax/controller/comment/CommentController.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentCreateRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/request/CommentModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/comment/dto/response/CommentResponse.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/request/IssuePostRequest.java
  be/src/main/java/com/issuetrackermax/controller/issue/dto/response/IssueDetailsResponse.java
  be/src/main/java/com/issuetrackermax/controller/member/MemberController.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/request/CheckLoginIdRequest.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/request/SignUpRequest.java
  be/src/main/java/com/issuetrackermax/domain/comment/CommentRepository.java
  be/src/main/java/com/issuetrackermax/domain/comment/entity/Comment.java
  be/src/main/java/com/issuetrackermax/domain/comment/entity/CommentMemberVO.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueStatus.java
  be/src/main/java/com/issuetrackermax/domain/member/MemberRepository.java
  be/src/main/java/com/issuetrackermax/domain/member/ProfileImage.java
  be/src/main/java/com/issuetrackermax/domain/member/entity/Member.java
  be/src/main/java/com/issuetrackermax/service/comment/CommentService.java
  be/src/main/java/com/issuetrackermax/service/issue/IssueService.java
  be/src/main/java/com/issuetrackermax/service/member/MemberService.java
  be/src/test/java/com/issuetrackermax/controller/auth/AuthControllerTest.java
  be/src/test/java/com/issuetrackermax/domain/comment/CommentRepositoryTest.java
  be/src/test/java/com/issuetrackermax/domain/member/MemberRepositoryTest.java
  be/src/test/java/com/issuetrackermax/fixture/EntityFixture.java
  be/src/test/java/com/issuetrackermax/service/comment/CommentServiceTest.java
Labels: feat, BE

#118 [FE] 이슈 및 코멘트 CRUD
  fe/src/App.tsx
  fe/src/assets/user/default.jpeg
  fe/src/components/Context/UserContext.tsx
  fe/src/components/FilterBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Issue/IssueContent.tsx
  fe/src/components/Issue/IssueCreate/IssueCreate.tsx
  fe/src/components/Issue/IssueDetail/Comment.tsx
  fe/src/components/Issue/IssueDetail/IssueDetail.tsx
  fe/src/components/Issue/IssueDetail/IssueDetailHeader.tsx
  fe/src/components/Issue/IssueDetail/SidebarDetail.tsx
  fe/src/components/Issue/IssueList/CheckBox.tsx
  fe/src/components/Issue/IssueList/IssueContext.tsx
  fe/src/components/Issue/IssueList/IssueFilter.tsx
  fe/src/components/Issue/IssueList/IssueItem.tsx
  fe/src/components/Issue/IssueList/IssueList.tsx
  fe/src/components/Label/Label.tsx
  fe/src/components/Label/LabelContext.tsx
  fe/src/components/Label/LabelItem.tsx
  fe/src/components/Label/LabelList.tsx
  fe/src/components/Milestone/MilestoneButton.tsx
  fe/src/components/Milestone/MilestoneContext.tsx
  fe/src/components/Milestone/MilestoneItem.tsx
  fe/src/components/Milestone/MilestoneList.tsx
  fe/src/components/Sign/SignIn.tsx
  fe/src/components/Sign/SignUp.tsx
  fe/src/components/Sign/common/CheckValidInfo.tsx
  fe/src/components/Sign/common/InputWithValidation.tsx
  fe/src/components/ThemeToggle.tsx
  fe/src/components/UserImageIcon.tsx
  fe/src/components/common/Button.tsx
  fe/src/styles/index.css
  fe/src/styles/styles.ts
  fe/src/type/Response.type.ts
  fe/src/type/User.type.ts
  fe/src/type/issue.d.ts
  fe/src/type/issue.type.ts
  fe/src/type/label.type.ts
  fe/src/type/milestone.type.ts
  fe/src/util/getKoreanTime.ts
  fe/src/util/getTimeLine.ts
Labels: FE

#130 [BE] 댓글, 레이블, 마일스톤 조회 기능 & 오류 수정
  be/src/main/java/com/issuetrackermax/controller/assignee/AssigneeController.java
  be/src/main/java/com/issuetrackermax/controller/comment/CommentController.java
  be/src/main/java/com/issuetrackermax/controller/filter/dto/response/MilestoneResponse.java
  be/src/main/java/com/issuetrackermax/controller/label/LabelController.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/request/LabelModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/response/LabelContentResponse.java
  be/src/main/java/com/issuetrackermax/controller/member/MemberController.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/response/MemberContentResponse.java
  be/src/main/java/com/issuetrackermax/controller/milestone/MilestoneController.java
  be/src/main/java/com/issuetrackermax/domain/assignee/AssigneeRepository.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueLabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/label/LabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/label/entity/Label.java
  be/src/main/java/com/issuetrackermax/domain/member/MemberRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/MilestoneRepository.java
  be/src/main/java/com/issuetrackermax/service/label/LabelService.java
  be/src/main/java/com/issuetrackermax/service/member/MemberService.java
  be/src/main/java/com/issuetrackermax/service/milestone/MilestoneService.java
Labels: feat, fix, BE

#131 [BE] 댓글, 레이블, 마일스톤 조회 기능 & 오류 수정
  be/src/main/java/com/issuetrackermax/controller/assignee/AssigneeController.java
  be/src/main/java/com/issuetrackermax/controller/comment/CommentController.java
  be/src/main/java/com/issuetrackermax/controller/filter/dto/response/MilestoneResponse.java
  be/src/main/java/com/issuetrackermax/controller/label/LabelController.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/request/LabelModifyRequest.java
  be/src/main/java/com/issuetrackermax/controller/label/dto/response/LabelContentResponse.java
  be/src/main/java/com/issuetrackermax/controller/member/MemberController.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/response/MemberContentResponse.java
  be/src/main/java/com/issuetrackermax/controller/milestone/MilestoneController.java
  be/src/main/java/com/issuetrackermax/domain/assignee/AssigneeRepository.java
  be/src/main/java/com/issuetrackermax/domain/history/HistoryRepository.java
  be/src/main/java/com/issuetrackermax/domain/issue/IssueLabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/label/LabelRepository.java
  be/src/main/java/com/issuetrackermax/domain/label/entity/Label.java
  be/src/main/java/com/issuetrackermax/domain/member/MemberRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/MilestoneRepository.java
  be/src/main/java/com/issuetrackermax/service/label/LabelService.java
  be/src/main/java/com/issuetrackermax/service/member/MemberService.java
  be/src/main/java/com/issuetrackermax/service/milestone/MilestoneService.java
Labels: feat, fix, BE

#132 [BE] 마일스톤 오류 수정
  be/src/main/java/com/issuetrackermax/controller/milestone/dto/request/MilestoneModifyRequest.java
  be/src/main/java/com/issuetrackermax/domain/milestone/MilestoneRepository.java
  be/src/main/java/com/issuetrackermax/domain/milestone/entity/Milestone.java
Labels: feat, fix, BE
