Repository codesquad-team4-issue-tracker/issue-tracker-max, pull requests merged in 2023-07, with the labels that each got.

#2 [FE] 프로젝트 초기 세팅
  fe/.gitignore
  fe/.prettierrc
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/assets/icons/alertCircle.svg
  fe/src/assets/icons/archive.svg
  fe/src/assets/icons/calendar.svg
  fe/src/assets/icons/checkBoxActive.svg
  fe/src/assets/icons/checkBoxDisable.svg
  fe/src/assets/icons/checkBoxInitial.svg
  fe/src/assets/icons/checkOffCircle.svg
  fe/src/assets/icons/checkOnCircle.svg
  fe/src/assets/icons/chevronDown.svg
  fe/src/assets/icons/edit.svg
  fe/src/assets/icons/label.svg
  fe/src/assets/icons/milestone.svg
  fe/src/assets/icons/paperclip.svg
  fe/src/assets/icons/plus.svg
  fe/src/assets/icons/refreshCcw.svg
  fe/src/assets/icons/search.svg
  fe/src/assets/icons/smile.svg
  fe/src/assets/icons/trash.svg
  fe/src/assets/icons/userImageLarge.svg
  fe/src/assets/icons/userImageSmall.svg
  fe/src/assets/icons/xSquare.svg
  fe/src/assets/logo/darkLarge.svg
  fe/src/assets/logo/darkMedium.svg
  fe/src/assets/logo/lightMedium.svg
  fe/src/assets/logo/ligthLarge.svg
  fe/src/main.tsx
  fe/src/styles/color.ts
  fe/src/styles/font.ts
  fe/src/styles/index.css
  fe/src/styles/object.ts
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
Labels: chore, FE

#10 [FE] 전체 UI 작업
  fe/src/App.tsx
  fe/src/assets/Logo/Logo.tsx
  fe/src/assets/icons/AlertCircleIcon.tsx
  fe/src/assets/icons/ArchiveIcon.tsx
  fe/src/assets/icons/CalendarIcon.tsx
  fe/src/assets/icons/CheckBoxIcon.tsx
  fe/src/assets/icons/CheckCircleIcon.tsx
  fe/src/assets/icons/ChevronDownIcon.tsx
  fe/src/assets/icons/EditIcon.tsx
  fe/src/assets/icons/LabelIcon.tsx
  fe/src/assets/icons/MilestoneIcon.tsx
  fe/src/assets/icons/PaperclipIcon.tsx
  fe/src/assets/icons/PlusIcon.tsx
  fe/src/assets/icons/RefreshIcon.tsx
  fe/src/assets/icons/SearchIcon.tsx
  fe/src/assets/icons/SmileIcon.tsx
  fe/src/assets/icons/TrashIcon.tsx
  fe/src/assets/icons/UserImageIcon.tsx
  fe/src/assets/icons/XSquareIcon.tsx
  fe/src/assets/logo/darkLarge.svg
  fe/src/assets/logo/darkMedium.svg
  fe/src/assets/logo/lightMedium.svg
  fe/src/assets/logo/ligthLarge.svg
  fe/src/components/Header/Header.tsx
  fe/src/components/Issue/IssueList/DropdownIndicator.tsx
  fe/src/components/Issue/IssueList/IssueItem.tsx
  fe/src/components/Issue/IssueList/IssueList.tsx
  fe/src/components/Label/Label.tsx
  fe/src/components/Milestone/Milestone.tsx
  fe/src/components/Sign/SignIn.tsx
  fe/src/components/Sign/SignUp.tsx
  fe/src/components/Sign/common/CheckValidInfo.tsx
  fe/src/components/Sign/common/SignButton.tsx
  fe/src/components/Sign/common/UserInput.tsx
  fe/src/components/common/Button.tsx
  fe/src/components/common/MainWrapper.tsx
  fe/src/components/common/MainWrapperHeader.tsx
  fe/src/components/common/Taps.tsx
  fe/src/styles/index.css
  fe/src/styles/object.ts
Labels: feat, design, FE

#11 [BE] OAuth (github) 통한 로그인 기능 구현 완료
  be/build.gradle
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/config/OauthConfig.java
  be/src/main/java/com/issuetrackermax/controller/auth/OAuthController.java
  be/src/main/java/com/issuetrackermax/controller/auth/dto/response/MemberProfileResponse.java
  be/src/main/java/com/issuetrackermax/controller/auth/dto/response/OauthTokenResponse.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/request/SignUpRequest.java
  be/src/main/java/com/issuetrackermax/domain/member/Entity/LoginType.java
  be/src/main/java/com/issuetrackermax/domain/member/Entity/Member.java
  be/src/main/java/com/issuetrackermax/domain/member/MemberRepository.java
  be/src/main/java/com/issuetrackermax/domain/oAuth/InMemoryProviderRepository.java
  be/src/main/java/com/issuetrackermax/domain/oAuth/entity/OauthAttributes.java
  be/src/main/java/com/issuetrackermax/domain/oAuth/entity/OauthProperties.java
  be/src/main/java/com/issuetrackermax/domain/oAuth/service/OauthProvider.java
  be/src/main/java/com/issuetrackermax/domain/oAuth/service/OauthService.java
  be/src/main/java/com/issuetrackermax/domain/oAuth/utils/OauthAdapter.java
  be/src/main/resources/schema.sql
Labels: feat, BE

#14 [BE] 리뷰 내용 반영 #13
  be/src/main/java/com/issuetrackermax/common/exception/JwtExceptionType.java
  be/src/main/java/com/issuetrackermax/common/filter/JwtAuthorizationFilter.java
  be/src/main/java/com/issuetrackermax/controller/ApiResponse.java
  be/src/main/java/com/issuetrackermax/controller/auth/OAuthController.java
  be/src/main/java/com/issuetrackermax/controller/auth/dto/response/JwtExceptionError.java
  be/src/main/java/com/issuetrackermax/controller/member/dto/request/SignUpRequest.java
  be/src/main/java/com/issuetrackermax/domain/jwt/service/JwtProvider.java
  be/src/main/java/com/issuetrackermax/domain/oauth/utils/OauthAdapter.java
  be/src/main/java/com/issuetrackermax/service/oauth/OauthProvider.java
  be/src/main/java/com/issuetrackermax/service/oauth/OauthService.java
  be/src/test/java/com/issuetrackermax/IssueTrackerMaxApplicationTests.java
  be/src/test/java/com/issuetrackermax/service/jwt/JwtServiceTest.java
  be/src/test/java/com/issuetrackermax/service/member/MemberServiceTest.java
  be/src/test/java/com/issuetrackermax/service/oauth/OauthServiceTest.java
Labels: style, refactor, fix, BE
